AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  HomeAppApi

Parameters:
  UserPool:
    Type: String
    Description: User pool for Cognito
  AccountId:
    Type: String
    Description: Account Id
  Region:
    Type: String
    Description: AWS Region
  Audience:
    Type: String
    Description: Client id for user pool

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  Api:
    TracingEnable: true
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Auth:
        Authorizers:
          CognitoAuthorizer:
            Type: CognitoAuthorizer
            AuthorizationScopes:
              - email
              - openid
              - profile
            UserPoolArn: !Sub arn:aws:cognito-idp:${Region}:${AccountId}:userpool/${Region}${UserPool}
        DefaultAuthorizer: CognitoAuthorizer

  MqttPublisherFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
      BuildTarget: build-MqttPublisherFunction
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        ControlGate:
          Type: Api
          Properties:
            Method: Post
            Path: /gates/control
            RestApiId: !Ref Api
            Auth:
              Authorizer: CognitoAuthorizer
              AuthorizationScopes:
                - !Sub Admins-${Audience}
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iot:Publish
              Resource: !Sub arn:aws:iot:${Region}:${AccountId}:topic/controlGate

  GetUserProfileImage:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
      BuildTarget: build-GetUserProfileImage
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        GetProfileImage:
          Type: Api
          Properties:
            Method: Get
            Path: /profile-image
            RestApiId: !Ref Api
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::jfolgado-homeapp-userprofile-v1/*